export enum ActionTypes {
  FETCH_USERS_START = "FETCH_USERS_START",
  FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE",
  ADD_USER = "ADD_USER",
  DELETE_USER = "DELETE_USER",
}
